name: Android Build

on:
  # 当有代码推送到main分支时触发工作流
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置Java环境为Java 17
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 授予gradlew执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 构建Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 上传Debug APK作为工件
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # 构建Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # 上传Release APK作为工件
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
